import {
  ElInput,
  ElInputNumber,
  ElAutocomplete,
  ElSelect,
  ElSwitch,
  ElCheckboxGroup,
  ElRadioGroup,
  ElColorPicker,
  ElDatePicker,
  ElTimePicker,
  ElTimeSelect,
  ElUpload,
  ElSlider,
  ElRate,
  ElProgress,
  ElSkeleton,
  ElSkeletonItem,
} from 'element-plus'

export const componentMap = {
  ElInput: ElInput,
  ElSelect: ElSelect,
  ElCheckboxGroup: ElCheckboxGroup,
  ElInputNumber: ElInputNumber,
  ElSwitch: ElSwitch,
  ElRadioGroup: ElRadioGroup,
  ElAutocomplete: ElAutocomplete,
  ElColorPicker: ElColorPicker,
  ElDatePicker: ElDatePicker,
  ElTimePicker: ElTimePicker,
  ElTimeSelect: ElTimeSelect,
  ElUpload: ElUpload,
  ElSlider: ElSlider,
  ElRate: ElRate,
  ElProgress: ElProgress,
  ElSkeleton: ElSkeleton,
  ElSkeletonItem: ElSkeletonItem,
}
